var searchData=
[
  ['s_5fi5g_17230',['s_i5g',['../structs__i5g.html',1,'']]],
  ['s_5fi5g_5finit_17231',['s_i5g_init',['../structs__i5g__init.html',1,'']]],
  ['sd_5fdesc_17232',['sd_desc',['../structsd__desc.html',1,'']]],
  ['sd_5finit_5fparam_17233',['sd_init_param',['../structsd__init__param.html',1,'']]],
  ['spi_5fdesc_17234',['spi_desc',['../structspi__desc.html',1,'']]],
  ['spi_5fdevice_17235',['spi_device',['../structspi__device.html',1,'']]],
  ['spi_5fengine_5fcmd_5fqueue_17236',['spi_engine_cmd_queue',['../structspi__engine__cmd__queue.html',1,'']]],
  ['spi_5fengine_5fdesc_17237',['spi_engine_desc',['../structspi__engine__desc.html',1,'']]],
  ['spi_5fengine_5finit_5fparam_17238',['spi_engine_init_param',['../structspi__engine__init__param.html',1,'']]],
  ['spi_5fengine_5fmsg_17239',['spi_engine_msg',['../structspi__engine__msg.html',1,'']]],
  ['spi_5fengine_5foffload_5finit_5fparam_17240',['spi_engine_offload_init_param',['../structspi__engine__offload__init__param.html',1,'']]],
  ['spi_5fengine_5foffload_5fmessage_17241',['spi_engine_offload_message',['../structspi__engine__offload__message.html',1,'']]],
  ['spi_5finit_5fparam_17242',['spi_init_param',['../structspi__init__param.html',1,'']]],
  ['spi_5fplatform_5fops_17243',['spi_platform_ops',['../structspi__platform__ops.html',1,'']]],
  ['spisettings_5ft_17244',['spiSettings_t',['../structspi_settings__t.html',1,'']]],
  ['std_5ftiming_17245',['std_timing',['../structstd__timing.html',1,'']]],
  ['strg_5fdesc_17246',['strg_desc',['../structstrg__desc.html',1,'']]],
  ['synthlut_17247',['SynthLUT',['../struct_synth_l_u_t.html',1,'']]]
];
